version: '3'
services:
  crypto-price-publisher:
    image: crypto-price-publisher:latest
    build:
      context: ./golang
      dockerfile: ./Dockerfile
    ports:
      - "8080:8080"
    expose:
      - 8080