version: '3'

services:
  crypto-price-publisher:
    image: crypto-price-publisher:latest
    build:
      context: ./golang
      dockerfile: ./Dockerfile
      args:
        SERVICE_NAME: cryptopricepublisher
        EXPOSE_PORT: 8086
    ports:
      - "8086:8086"
    expose:
      - 8086

  twitter-stream-producer:
    image: twitter-stream-producer:latest
    build:
      context: ./golang
      dockerfile: ./Dockerfile
      args:
        SERVICE_NAME: twitterstreamproducer
        EXPOSE_PORT: 8087
    ports:
      - "8087:8087"
    expose:
      - 8087

  krakend-api-gateway:
    image: devopsfaith/krakend:latest
    volumes:
      - ./infrastructure/apigateway:/etc/krakend
    ports:
      - "8080:8080"
    depends_on:
      - crypto-price-publisher
      - twitter-stream-producer

volumes:
  krakend: