version: '3'
services:
  crypto-price-publisher:
    image: crypto-price-publisher:latest
    build:
      context: ./golang
      dockerfile: ./Dockerfile
    ports:
      - "8081:8081"
    expose:
      - 8081
  krakend-api-gateway:
    image: devopsfaith/krakend:latest
    volumes:
      - ./infrastructure/apigateway:/etc/krakend
    ports:
      - "8080:8080"
    depends_on:
      - crypto-price-publisher
  whisper-ui:
    image: whisper-ui:latest
    build:
      context: ./nodejs
      dockerfile: ./Dockerfile
    ports:
      - "3000:3000"
    expose:
      - 3000
    depends_on:
      - krakend-api-gateway