name: build-master

on:
  push:
    branches:
      - master

jobs:
  build-master:
    runs-on: ubuntu-latest
    steps:
      - name: checkout master
        uses: actions/checkout@master

      - name: setup golang
        uses: actions/setup-go@v2
        with:
          go-version: '1.15'

      - name: run unit tests
        run: |
          go version
          go clean
          go test ./...
        working-directory: ./golang