name: Gource Action
on:
  push:
    branches:
      - master

jobs:
  action:
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: 'Gource Action'
        uses: nbprojekt/gource-action@v1
        with:
          gource_title: go-whispers
          gource_overlay_background_color: '0a0a0a'
          gource_hide_items: 'mouse,date,progress'

      - name: 'Upload gource video'
        uses: actions/upload-artifact@v2
        with:
          name: Gource
          path: ./gource/gource.mp4
